# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(1, '\u822a\u73ed'), (2, '\u9ad8\u94c1'), (3, '\u6d3b\u529b'), (4, 'localytics')], unique=True, verbose_name='\u7c7b\u522b\u4ee3\u7801')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u6a21\u5757\u5927\u7c7b',
                'verbose_name_plural': '\u6a21\u5757\u5927\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='ErrorJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_day', models.CharField(max_length=20, verbose_name='\u65e5\u671f')),
            ],
            options={
                'db_table': 'error_update_table_daily',
                'verbose_name': '\u672a\u66f4\u65b0\u6210\u529f\u7684\u4efb\u52a1',
                'verbose_name_plural': '\u672a\u66f4\u65b0\u6210\u529f\u7684\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u51fd\u6570')),
                ('job_path', models.CharField(max_length=200, verbose_name='\u4efb\u52a1\u8def\u5f84')),
                ('job_desc', models.CharField(max_length=500, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('job_table', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u8868\u540d')),
                ('job_type', models.IntegerField(choices=[(1, '\u6bcf\u5929\u66f4\u65b0\u7684\u4efb\u52a1'), (2, '\u6bcf\u5468\u66f4\u65b0\u7684\u4efb\u52a1'), (3, '\u6bcf\u6708\u66f4\u65b0\u7684\u4efb\u52a1'), (4, '\u6bcf\u5b63\u5ea6\u66f4\u65b0'), (5, '\u53d1\u9001\u90ae\u4ef6')], verbose_name='\u4efb\u52a1\u6240\u5c5e\u7c7b\u578b')),
                ('is_execute', models.BooleanField(default=1, verbose_name='\u80fd\u5426\u76f4\u63a5\u6267\u884c')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_nodes', to='jobs.Category', verbose_name='\u4efb\u52a1\u6240\u5c5e\u7c7b\u522b')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name_plural': '\u4efb\u52a1',
                'db_table': 'bi_execute_job',
                'verbose_name': '\u4efb\u52a1',
            },
        ),
        migrations.AddField(
            model_name='errorjob',
            name='error_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('job_name', 'job_table')]),
        ),
        migrations.AlterUniqueTogether(
            name='errorjob',
            unique_together=set([('s_day', 'error_job')]),
        ),
    ]
