# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_desc',
            new_name='job_doc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(choices=[(1, '\u822a\u73ed'), (2, '\u9ad8\u94c1'), (3, '\u6d3b\u529b'), (4, 'localytics')], primary_key=True, serialize=False, unique=True, verbose_name='\u7c7b\u522b\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='errorjob',
            name='error_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='errorjob',
            name='s_day',
            field=models.CharField(max_length=50, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterUniqueTogether(
            name='errorjob',
            unique_together=set([]),
        ),
    ]
